winter:
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000ms
    timeout: 2000ms  # 连接超时时间
#    password: yourpassword  # 6.0之前暂不支持user和password